### ISSUE TITLE
Whitelabel Error Page

### ISSUE THREAD

**Issue by ymalikov** [alexoooo/kzen-shell#10]
what happened: i opened a newly created project while closing a project that was running. Maybe that caused it. not sure to be honest.

This application has no configured error view, so you are seeing this as a fallback.

Sat Dec 29 12:47:43 EST 2018
There was an unexpected error (type=Internal Server Error, status=500).
Unknown project: Kijij%20repo%20repost

**Comment by ymalikov** [comment]
looks like project with spaces in the name get this error on start up

**Comment by alexoooo** [comment]
Added support for spaces in Project name

**Comment by ymalikov** [comment]
:)
